"""Initial migration

Revision ID: 45a1208cb4f1
Revises: 
Create Date: 2020-05-28 23:47:55.640703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45a1208cb4f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_last_time',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('last_time', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrapper_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scrapper_name', mysql.TEXT(), nullable=False),
    sa.Column('headline', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('date_time', mysql.TEXT(), nullable=True),
    sa.Column('article', mysql.LONGTEXT(), nullable=True),
    sa.Column('story_kicker', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_source',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scrapper_config_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['scrapper_config_id'], ['scrapper_config.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('rss_feed',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('link', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('title', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('summary', mysql.LONGTEXT(), nullable=True),
    sa.Column('published_string', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['source_url'], ['rss_source.url'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_feed_scrapped',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rss_feed_id', sa.BigInteger(), nullable=True),
    sa.Column('uri', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('headline', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('story_kicker', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('article', mysql.LONGTEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['rss_feed_id'], ['rss_feed.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_feeds_link',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rss_feed_id', sa.BigInteger(), nullable=True),
    sa.Column('rss_feed_link', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['rss_feed_id'], ['rss_feed.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_feeds_link')
    op.drop_table('rss_feed_scrapped')
    op.drop_table('rss_feed')
    op.drop_table('rss_source')
    op.drop_table('scrapper_config')
    op.drop_table('rss_last_time')
    # ### end Alembic commands ###
